// <auto-generated />
namespace MovieRentalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedrequiredannotationfrommovieclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedrequiredannotationfrommovieclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201906062019095_removed required annotation from movie class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
