// <auto-generated />
namespace MovieRentalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class genremoviemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genremoviemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201905251119533_genre-movie model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
